spring:
  application:
    name: course-distributor

  datasource:
    url: jdbc:postgresql://ep-floral-king-aqbf3zr6-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_kDKiRjSIu27d
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    # properties:
    #   hibernate:
    #     format_sql: true
    #     jdbc:
    #       time_zone: Asia/Kolkata
    
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration: 604800000